Prevent from accidental exiting of zypper.
Zypper comand exit with non-zero if all repositories are up
to date. Here is the log:

 + zypper --non-interactive ref
 Retrieving repository 'home:/tester:/Tools-mic-8596.3' metadata [.error]
 Repository 'home:/tester:/Tools-mic-8596.3' is invalid.
 [|] Valid metadata not found at specified URL(s)
 Please check if the URIs defined for this repository are pointing to a valid repository.
 Skipping repository 'home:/tester:/Tools-mic-8596.3' because of the above error.
 Repository 'openSUSE-12.2 Updates, FI-mirror' is up to date.
 Repository 'repo-oss' is up to date.
 Retrieving repository 'tools-ToolsDevel' metadata [..done]
 Building repository 'tools-ToolsDevel' cache [....done]
 Repository 'tools-hometesterWorkers' is up to date.
 Repository 'tools-itest' is up to date.
 Some of the repositories have not been refreshed because of an error.
 + End
 + '[' -f /var/log/messages ']'
 + tail -50 /var/log/messages

Counterpart of yum and apt-get don't have this side effect.
 yum -y clean all
 apt-get update
These two commands always exit 0 even there is nothing to do.

Change-Id: Ie9a5c0b31d8c35b9101d2f87a326bef3d4914d6e

diff --git a/install_package b/install_package
--- a/install_package
+++ b/install_package
@@ -76,7 +76,8 @@ elif [ -x /usr/bin/zypper -a -d /etc/zypp/repos.d ] ; then
    reponame="tools-`echo \"$sproject\" | tr -d '[:punct:][:space:]'`"
    [ -n "$sproject" ] && zypper ar -fG http://download.otctools.jf.intel.com/$sproject/$repo/ $reponame
    [ -n "$extra_repos" ] && add_extra_repos $run_on "$extra_repos" ""
-   zypper --non-interactive ref
+   # zypper exit nonzero if all repositories are up to date
+   zypper --non-interactive ref || true
    [ "$noupd" != "noupdate" ] && zypper --non-interactive up
    install_pkgs "zypper --non-interactive install" "$testreq_packages" "$packages"
 elif [ \( -x /bin/yum -o -x /usr/bin/yum \) -a -d /etc/yum.repos.d ] ; then
